version: '3'
services:
  web-client-htmx:
    image: web_htmx
    build:
      context: ./clients/web_htmx
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      client-network:
        aliases:
          - web_client
    environment:
      GATEWAY_ENDPOINT: "gateway:3000"

  api-gateway:
    image: api-gateway
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      client-network:
        aliases:
          - gateway
      gateway-network:
        aliases:
          - gateway
    environment:
      VIDEO_SERVICE_ENDPOINT: "video-service:3001"

  video-service:
    image: video-service
    build:
      context: ./services/video_service
      dockerfile: Dockerfile
    networks:
      gateway-network:
        aliases:
          - video-service
      minio-network:
        aliases:
          - video-service
    environment:
      MINIO_ROOT_USER: "ROOTNAME"
      MINIO_ROOT_PASSWORD: "CHANGEME123"
      S3_ENDPOINT: "minio-s3:9000"

  minio-s3:
    image: "quay.io/minio/minio"
    command: server /minio-data --console-address ":9090"
    ports:
    #  - 9000:9000
      - 9090:9090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - "./minio:/data"
    networks:
      minio-network:
        aliases:
          - minio-s3
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123

networks:
  client-network:
    name: client-network
  gateway-network:
    name: gateway-network
  minio-network:
    name: minio-network
