// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: cdn.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data         []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ChunkIdx     int32  `protobuf:"varint,2,opt,name=chunk_idx,json=chunkIdx,proto3" json:"chunk_idx,omitempty"`
	NextChunkIdx int32  `protobuf:"varint,3,opt,name=next_chunk_idx,json=nextChunkIdx,proto3" json:"next_chunk_idx,omitempty"`
}

func (x *VideoChunk) Reset() {
	*x = VideoChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoChunk) ProtoMessage() {}

func (x *VideoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoChunk.ProtoReflect.Descriptor instead.
func (*VideoChunk) Descriptor() ([]byte, []int) {
	return file_cdn_proto_rawDescGZIP(), []int{0}
}

func (x *VideoChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VideoChunk) GetChunkIdx() int32 {
	if x != nil {
		return x.ChunkIdx
	}
	return 0
}

func (x *VideoChunk) GetNextChunkIdx() int32 {
	if x != nil {
		return x.NextChunkIdx
	}
	return 0
}

type VideoChunkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId  string `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ChunkIdx int32  `protobuf:"varint,2,opt,name=chunk_idx,json=chunkIdx,proto3" json:"chunk_idx,omitempty"`
}

func (x *VideoChunkRequest) Reset() {
	*x = VideoChunkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoChunkRequest) ProtoMessage() {}

func (x *VideoChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoChunkRequest.ProtoReflect.Descriptor instead.
func (*VideoChunkRequest) Descriptor() ([]byte, []int) {
	return file_cdn_proto_rawDescGZIP(), []int{1}
}

func (x *VideoChunkRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoChunkRequest) GetChunkIdx() int32 {
	if x != nil {
		return x.ChunkIdx
	}
	return 0
}

type RecentVideosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Range  int32 `protobuf:"varint,2,opt,name=range,proto3" json:"range,omitempty"`
}

func (x *RecentVideosRequest) Reset() {
	*x = RecentVideosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdn_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecentVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentVideosRequest) ProtoMessage() {}

func (x *RecentVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentVideosRequest.ProtoReflect.Descriptor instead.
func (*RecentVideosRequest) Descriptor() ([]byte, []int) {
	return file_cdn_proto_rawDescGZIP(), []int{2}
}

func (x *RecentVideosRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RecentVideosRequest) GetRange() int32 {
	if x != nil {
		return x.Range
	}
	return 0
}

type RecentVideos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId          string `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	VideoTitle       string `protobuf:"bytes,2,opt,name=video_title,json=videoTitle,proto3" json:"video_title,omitempty"`
	VideoThumbnailId string `protobuf:"bytes,3,opt,name=video_thumbnail_id,json=videoThumbnailId,proto3" json:"video_thumbnail_id,omitempty"`
	UploadDate       string `protobuf:"bytes,4,opt,name=upload_date,json=uploadDate,proto3" json:"upload_date,omitempty"`
}

func (x *RecentVideos) Reset() {
	*x = RecentVideos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdn_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecentVideos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentVideos) ProtoMessage() {}

func (x *RecentVideos) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentVideos.ProtoReflect.Descriptor instead.
func (*RecentVideos) Descriptor() ([]byte, []int) {
	return file_cdn_proto_rawDescGZIP(), []int{3}
}

func (x *RecentVideos) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *RecentVideos) GetVideoTitle() string {
	if x != nil {
		return x.VideoTitle
	}
	return ""
}

func (x *RecentVideos) GetVideoThumbnailId() string {
	if x != nil {
		return x.VideoThumbnailId
	}
	return ""
}

func (x *RecentVideos) GetUploadDate() string {
	if x != nil {
		return x.UploadDate
	}
	return ""
}

var File_cdn_proto protoreflect.FileDescriptor

var file_cdn_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x64, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x22, 0x63, 0x0a, 0x0a, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64, 0x78, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x65,
	0x78, 0x74, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64, 0x78,
	0x22, 0x4b, 0x0a, 0x11, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64, 0x78, 0x22, 0x43, 0x0a,
	0x13, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x22, 0x99, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x2c, 0x0a, 0x12, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x74, 0x65, 0x32, 0xc2,
	0x01, 0x0a, 0x15, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x21, 0x2e, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67,
	0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x56, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x12, 0x23,
	0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e,
	0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x73, 0x30, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6a, 0x61, 0x63, 0x6b, 0x6a, 0x6f, 0x68, 0x6e, 0x37, 0x2f, 0x77, 0x65, 0x62, 0x76,
	0x69, 0x65, 0x77, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cdn_proto_rawDescOnce sync.Once
	file_cdn_proto_rawDescData = file_cdn_proto_rawDesc
)

func file_cdn_proto_rawDescGZIP() []byte {
	file_cdn_proto_rawDescOnce.Do(func() {
		file_cdn_proto_rawDescData = protoimpl.X.CompressGZIP(file_cdn_proto_rawDescData)
	})
	return file_cdn_proto_rawDescData
}

var file_cdn_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cdn_proto_goTypes = []interface{}{
	(*VideoChunk)(nil),          // 0: videoStreaming.VideoChunk
	(*VideoChunkRequest)(nil),   // 1: videoStreaming.VideoChunkRequest
	(*RecentVideosRequest)(nil), // 2: videoStreaming.RecentVideosRequest
	(*RecentVideos)(nil),        // 3: videoStreaming.RecentVideos
}
var file_cdn_proto_depIdxs = []int32{
	1, // 0: videoStreaming.VideoStreamingService.StreamVideoChunk:input_type -> videoStreaming.VideoChunkRequest
	2, // 1: videoStreaming.VideoStreamingService.GetRecentVideos:input_type -> videoStreaming.RecentVideosRequest
	0, // 2: videoStreaming.VideoStreamingService.StreamVideoChunk:output_type -> videoStreaming.VideoChunk
	3, // 3: videoStreaming.VideoStreamingService.GetRecentVideos:output_type -> videoStreaming.RecentVideos
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cdn_proto_init() }
func file_cdn_proto_init() {
	if File_cdn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cdn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoChunkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdn_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecentVideosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdn_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecentVideos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cdn_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cdn_proto_goTypes,
		DependencyIndexes: file_cdn_proto_depIdxs,
		MessageInfos:      file_cdn_proto_msgTypes,
	}.Build()
	File_cdn_proto = out.File
	file_cdn_proto_rawDesc = nil
	file_cdn_proto_goTypes = nil
	file_cdn_proto_depIdxs = nil
}
